version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin@123
      MONGO_INITDB_DATABASE: admin
    command: mongod --bind_ip_all --auth
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge